apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cart
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - image: robotshop/rs-cart:0.2.2
        name: cart
        ports:
        - name: cart-port
          containerPort: 8080
