apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  type: NodePort
  selector:
    app: catalogue
  ports:
    - port: 31004
      nodePort: 31004
      targetPort: catalogue-port
      protocol: TCP
