apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogue
  name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - image: robotshop/rs-catalogue:0.2.2
        name: catalogue
        ports:
        - name: catalogue-port
          containerPort: 8080
