apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dispatch
  name: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
      - image: robotshop/rs-dispatch:0.2.2
        name: dispatch
        resources: {}
      restartPolicy: Always
