apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: robotshop/rs-shipping-db:0.2.2
        name: mysql
        ports:
        - name: mysql-port
          containerPort: 3306
