apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: robotshop/rs-payment:0.2.2
        name: payment
        ports:
        - name: payment-port
          containerPort: 8080
