apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipping
  name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shipping
    spec:
      containers:
      - image: robotshop/rs-shipping:0.2.2
        name: shipping
        ports:
        - containerPort: 8080
