apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipping
  name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - image: robotshop/rs-shipping:0.2.2
        name: shipping
        ports:
        - name: shipping-port 
          containerPort: 8080
