apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  type: NodePort
  selector:
    app: shipping
  ports:
  - port: 31008
    nodePort: 31008
    targetPort: shipping-port
    protocol: TCP
