apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: robotshop/rs-user:0.2.2
        name: user
        ports:
        - name: user-port
          containerPort: 8080
